<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Internal;

if (false) {
    /**
     * This class is deprecated. Use Google\Protobuf\Internal\FileOptions\JavaBeanStyle instead.
     * @deprecated
     */
    class FileOptions_JavaBeanStyle {}
}
class_exists(FileOptions\JavaBeanStyle::class);
@trigger_error('Google\Protobuf\Internal\FileOptions_JavaBeanStyle is deprecated and will be removed in the next major release. Use Google\Protobuf\Internal\FileOptions\JavaBeanStyle instead', E_USER_DEPRECATED);

