<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Internal\FileOptions;

/**
 * Java Bean style of Get/Set Methods
 *
 * Protobuf type <code>google.protobuf.FileOptions.JavaBeanStyle</code>
 */
class JavaBeanStyle
{
    /**
     * Returns a default instance value, set throws NPE if passed null
     *
     * Generated from protobuf enum <code>DEFAULT_INSTANCE = 1;</code>
     */
    const DEFAULT_INSTANCE = 1;
    /**
     * Set and Get throw a Null Pointer Exception if the value is null
     *
     * Generated from protobuf enum <code>FAIL_FAST = 2;</code>
     */
    const FAIL_FAST = 2;
    /**
     * Get returns null, set accepts null and clears the value
     *
     * Generated from protobuf enum <code>NULL_CLEAR = 3;</code>
     */
    const NULL_CLEAR = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(JavaBeanStyle::class, \Google\Protobuf\Internal\FileOptions_JavaBeanStyle::class);

